import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#525c89",
        "on-error-container": "#93000a",
        "surface-container": "#ebeef2",
        "on-surface-variant": "#444653",
        "on-secondary-fixed": "#0d1842",
        "primary-fixed": "#dde1ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdad2",
        tertiary: "#530c00",
        "tertiary-container": "#7a1801",
        "on-primary-fixed-variant": "#1439af",
        "surface-container-high": "#e5e8ec",
        "secondary-container": "#c0c9fd",
        primary: "#001e73",
        "outline-variant": "#c4c5d6",
        "on-tertiary-fixed": "#3d0700",
        "surface-variant": "#e0e3e7",
        "surface-container-highest": "#e0e3e7",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3134",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001355",
        "surface-tint": "#3654c8",
        "on-tertiary-container": "#ff876a",
        background: "#f7fafe",
        "secondary-fixed": "#dde1ff",
        "surface-bright": "#f7fafe",
        "secondary-fixed-dim": "#bac4f8",
        "on-primary-container": "#90a4ff",
        "tertiary-fixed-dim": "#ffb4a3",
        "primary-fixed-dim": "#b8c4ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4a5480",
        "on-background": "#181c1f",
        "inverse-on-surface": "#eef1f5",
        "surface-container-low": "#f1f4f8",
        "primary-container": "#002fa7",
        "on-surface": "#181c1f",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3a4470",
        "on-primary": "#ffffff",
        "surface-dim": "#d7dade",
        "on-tertiary-fixed-variant": "#872108",
        "inverse-primary": "#b8c4ff",
        outline: "#757685",
        error: "#ba1a1a",
        surface: "#f7fafe",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      fontFamily: {
        headline: ["var(--font-ibm-plex-sans)", "sans-serif"],
        body: ["var(--font-ibm-plex-serif)", "serif"],
        label: ["var(--font-jetbrains-mono)", "monospace"],
        sans: ["var(--font-ibm-plex-sans)", "sans-serif"],
        serif: ["var(--font-ibm-plex-serif)", "serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      boxShadow: {
        custom: "0 20px 40px rgba(0, 30, 115, 0.06)",
      },
      animation: {
        "tree-expand": "tree-expand 20s ease-in-out infinite",
        "path-draw": "path-draw 10s linear infinite",
        "node-pulse": "node-pulse 4s ease-in-out infinite",
      },
      keyframes: {
        "tree-expand": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.2" },
          "50%": { transform: "scale(1.05)", opacity: "0.4" },
        },
        "path-draw": {
          "0%": { strokeDashoffset: "1000", opacity: "0" },
          "50%": { opacity: "0.5" },
          "100%": { strokeDashoffset: "0", opacity: "0.1" },
        },
        "node-pulse": {
          "0%, 100%": { r: "4", opacity: "0.4" },
          "50%": { r: "6", opacity: "0.8" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
